apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-stack
  namespace: argocd
  labels:
    stack: myapp
    manager: argocd
spec:
  description: Project for MyApp tech stack (Nginx, Redis, Go)
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
